site_name: Opinion cursos Kike Arnaiz
site_url: https://opinioncursosfotografiakikearnaiz.com
site_description: Opiniones sobre los cursos de Kike Arnaiz antes de comprar

nav:
  - Inicio: index.md
  - ¿Quién es Kike Arnaiz?: kike-arnaiz.md
  - Iniciacion a la fotografia: curso-fotografia-desde-cero.md
  - Retoque fotográfico: curso-retoque-fotografico.md
  - Composicion fotográfica: curso-composicion-fotografia.md
  - Fotografía retrato: curso-fotografia-retrato.md
  - Pack de cursos: pack-cursos-fotografia.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  palette:
    primary: teal
    accent: teal
  name: material
  language: es
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - announce.dismiss
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - stylesheets/home.css
        - stylesheets/extra.css
# - blog:
#     blog_dir: .
#     blog_toc: false
#     archive: false
#     categories: false
#     post_readtime: false

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      url_download: true
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: GOOGLE_ANALYTICS_KEY
  generator: false
  consent:
    title: Cookie consent
    description: >
      This website uses cookies to ensure you get the best experience on our website.
      <a href="/conditions/cookie-policy/" target="_blank">See cookie policy</a>
    cookies:
      analytics:
        name: Google Analytics
        checked: true

extra_css:
  - stylesheets/home.css
  - stylesheets/extra.css

copyright: >
  2025 &copy; opinion cursos fotografia Kike Arnaiz –
  <a href="#__consent">Change cookie settings</a>
